language: csharp

# dotnet cli require Ubuntu 14.04
sudo: required
#dist: xenial

os:
  - linux

# dotnet cli require OSX 10.10
#osx_image: xcode7.1

#addons:
#  apt:
#    packages:
#    - nuget
#    - mono-complete

language: csharp
#solution: TweetNaCl.sln

mono:
  - latest

install:
  - nuget restore src/TweetNaCl.sln
  - nuget install NUnit.Runners -Version 3.0.1 -OutputDirectory testrunner

script:
  - xbuild /p:Configuration=Release ./src/TweetNaCl.sln
  - mono ./testrunner/NUnit.Console.3.0.1/tools/nunit3-console.exe src/TweetNaCl.Tests/bin/Release/TweetNaCl.Tests.dll
