#language: csharp
solution: TweetNaCl.sln

mono:
  - latest

install:
  - nuget restore src/TweetNaCl.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner

script:
  - xbuild /p:Configuration=Release src/TweetNaCl.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe src/TweetNaCl.Tests/bin/Release/TweetNaCl.Tests.dll

