#language: csharp
#solution: TweetNaCl.sln

# dotnet cli require Ubuntu 14.04
sudo: required
dist: xenial

mono:
  - latest
  
install:
  - sudo apt-get install -y curl nuget
  - nuget.exe restore ./src/TweetNaCl.sln
  - nuget.exe install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner

script:
  - xbuild /p:Configuration=Release ./src/TweetNaCl.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./src/TweetNaCl.Tests/bin/Release/TweetNaCl.Tests.dll

