#language: csharp
solution: TweetNaCl.sln

# dotnet cli require Ubuntu 14.04
sudo: required
dist: trusty

install:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  - echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
  - sudo apt-get update
  - sudo apt-get install -y libunwind8 libssl-dev unzip mono-complete libicu-dev libunwind8 gettext libssl-dev libcurl3-gnutls zlib1g sqlite3 libsqlite3-dev
  - nuget restore ./src/TweetNaCl.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner

script:
  - xbuild /p:Configuration=Release ./src/TweetNaCl.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./src/TweetNaCl.Tests/bin/Release/TweetNaCl.Tests.dll

