#language: csharp

# dotnet cli require Ubuntu 14.04
sudo: required
dist: trusty

# dotnet cli require OSX 10.10
#osx_image: xcode7.1

addons:
  apt:
    packages:
    - dotnet-dev-1.0.0-preview2-003121


os:
#  - osx
  - linux

env:
  - CLI_VERSION=latest

before_install:
  # Install OpenSSL
  - if test "$TRAVIS_OS_NAME" == "osx"; then
      brew update;
      brew install openssl;
      brew link --force openssl;
    fi

  - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
  - sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
  - sudo apt-get update

install:


script:
  - dotnet restore src/

  # testing only netcoreapp1.0 on linux and osx
- dotnet test src/NetMQ.Tests -f netcoreapp1.0 --labels=All
