language: csharp
solution: TweetNaCl.sln

mono:
  - latest

install:
  - nuget restore TweetNaCl.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
  
  script:
  - xbuild /p:Configuration=Release TweetNaCl.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./TweetNaCl.Tests/bin/Release/TweetNaCl.Tests.dll
